# Generated by Django 3.2.16 on 2024-10-07 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subscription_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.CharField(auto_created=datetime.datetime(2024, 10, 7, 11, 6, 35, 431098), default='', max_length=50),
        ),
    ]
